### ISSUE TITLE
Can't find reference 'FisherVectorGMM' in 'fishervector.py'

### ISSUE THREAD

**Issue by jvel07** [jonasrothfuss/fishervector#2]
Hi! Congrats for your job, I would like to try it out and use it for my investigation but after installing it via pip, I try to do `from fishervector import FisherVectorGMM` and FisherVectorGMM is not recognized. What is the workaround in this case?

**Comment by jonasrothfuss** [comment]
Have you added the fishervector repo/folder to your PYTHONPATH?

**Comment by jvel07** [comment]
You mean your whole repo? I am working on PyCharm using virtual environments. For the installation I just followed your installation instruction steps and nothing else. :)

**Comment by jvel07** [comment]
No need to add the repo to the PYTHONPATH, I was having a former class with the same name fishervector.py, that was the problem. Thanks!
